### ISSUE TITLE
how to train model on my own dataset? thanks your efforts

### ISSUE THREAD

**Issue by XiangBaoSong** [owenzlz/PA4Inpaint#2]

**Comment by owenzlz** [comment]
This would require changing the path of data in the configs. Since MMSeg has updated its API, I would recommend you start from our latest codebase: [https://github.com/owenzlz/PAL4VST](https://github.com/owenzlz/PAL4VST). Please also feel free to refer to the mmsegmentation documentation regarding the details of using this codebase.
